name: Build on PR

on:
  pull_request:
    branches:
      - main


jobs:
  build-linux-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            libasound2-dev \
            libgl1-mesa-dev \
            libglfw3-dev \
            xorg-dev \
            gcc-mingw-w64-x86-64

      - name: Set up environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.5'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --snapshot --clean --config .goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-linux-windows
          path: dist/
          retention-days: 1

  build-macos-arm64:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Ensure Xcode tools
        run: sudo xcode-select --install || true
      - name: Install deps
        run: |
          brew install pkg-config glfw
          export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH  
          export CGO_LDFLAGS="-L/usr/local/lib" 
          echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=$CGO_LDFLAGS" >> $GITHUB_ENV
      - name: Set up environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.5'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --snapshot --clean --config .goreleaser-macos-arm64.yaml  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-macos
          path: dist/
          retention-days: 1
  
  build-macos-intel:
    runs-on: macos-15-intel
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Ensure Xcode tools
        run: sudo xcode-select --install || true
      - name: Install deps
        run: |
          brew install pkg-config glfw
          export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH  
          export CGO_LDFLAGS="-L/usr/local/lib"  
          echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=$CGO_LDFLAGS" >> $GITHUB_ENV
      - name: Set up environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.5'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --snapshot --clean --config .goreleaser-macos-intel.yaml  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-macos
          path: dist/
          retention-days: 1

  release:
    needs: [build-linux-windows, build-macos-intel, build-macos-arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Linux/Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-linux-windows
          path: dist/

      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-macos
          path: dist/
          merge-multiple: true

      - name: Set up environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.4'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: continue --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
